// Grille des prix CEP - genere depuis GRILLE_DES_PRIX.xlsx
// Prix HT en euros. unite = "u" (piece) ou "m" (par metre).
const GRILLE_CEP = [
  { categorie: 'Cables', nom: '3G0,75 / 100m 007805 (GRIS) 007705 (BLANC)', prix: 1.1, unite: 'm' },
  { categorie: 'Cables', nom: '3G1,5 / 100m FRN1X6G3U3G1,5C100M', prix: 2.2, unite: 'm' },
  { categorie: 'Cables', nom: '3G2,5 / 100m FRN1X6G3U3G2,5C100M', prix: 3.5, unite: 'm' },
  { categorie: 'Cables', nom: '5G1,5 / 100m FRN1X6G3U5G1,5C100M', prix: 3.8, unite: 'm' },
  { categorie: 'Cables', nom: '5G2,5 / 100m FRN1X6G3U5G2,5C100M', prix: 5.5, unite: 'm' },
  { categorie: 'Cables', nom: '5G6 / 50m FRN1X6G3R5G6C50M', prix: 6.5, unite: 'm' },
  { categorie: 'Cables', nom: '5G10 / 1m', prix: 14, unite: 'm' },
  { categorie: 'Cables', nom: '5G16 / 1m', prix: 22, unite: 'm' },
  { categorie: 'Cables', nom: '4X35 / 1m', prix: 50, unite: 'm' },
  { categorie: 'Cables', nom: '3G1,5 PYROLION / 1m CR1C1', prix: 3, unite: 'm' },
  { categorie: 'Cables', nom: '3G2,5 PYROLION / 1m CR1C1', prix: 4.35, unite: 'm' },
  { categorie: 'Cables', nom: '5G2,5 PYROLION / 1m CR1C1', prix: 6.5, unite: 'm' },
  { categorie: 'Cables', nom: 'CABLE INFO 4P CATEGORIE 6 300m ACOM', prix: 1.8, unite: 'm' },
  { categorie: 'Cables', nom: 'CABLE SONO 2X1,5 AVEC ISOLANT 100m', prix: 3.4, unite: 'm' },
  { categorie: 'Cables', nom: 'GAINE GRISE DIAMETRE 20 ICTA', prix: 1, unite: 'm' },
  { categorie: 'Cables', nom: 'CABLE 2X1,5 PLAT NOIR ET ROUGE / 100M (SONEPAR)', prix: 1.8, unite: 'm' },
  { categorie: 'Disjoncteurs Mono', nom: '2A MONO 6kA C A9P22602', prix: 44, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: '4A MONO 6kA C A9P22604', prix: 48, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: '10A MONO 6kA C A9P22610', prix: 34, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: '16A MONO 6kA C A9P22616', prix: 34, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: '20A MONO 6kA C A9P22620', prix: 38, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 25A 30mA TYPE AC MONO A9Y12625', prix: 210, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 25A 300mA TYPE AC MONO A9Y13625', prix: 230, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: '32A MONO 6kA C A9P22632', prix: 42, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 40A 30mA TYPE AC MONO A9Y12640', prix: 240, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 40A 300mA TYPE AC MONO A9Y13640', prix: 230, unite: 'u' },
  { categorie: 'Disjoncteurs Mono', nom: '40A MONO 6kA C A9P22640', prix: 52, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '10A TETRA 6kA C A9P22710', prix: 145, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '16A TETRA 6kA C A9P22716', prix: 145, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '20A TETRA 6kA C A9P22720', prix: 125, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 25A 30mA TYPE AC TETRA A9Y12725', prix: 310, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 25A 300mA TYPE AC TETRA A9Y13725', prix: 240, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '32A TETRA 6kA C A9P22732', prix: 145, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '40A TETRA 6kA C A9P22740', prix: 205, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 40A 30mA TYPE AC TETRA A9Y12740', prix: 345, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 40A 300mA TYPE AC TETRA A9Y13740', prix: 245, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'BOBINE iMX+OF ACTI9 A9A26946', prix: 125, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '63A TETRA 10kA C A9P24463 (DT60N)', prix: 350, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 63A 30mA TYPE AC TETRA A9Y12463', prix: 530, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'BOBINE MX + OF A9N26946', prix: 120, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: '80A TETRA 10kA C A9N18373 (C120N)', prix: 590, unite: 'u' },
  { categorie: 'Disjoncteurs Tetra', nom: 'DIFFERENTIEL VIGI TETE DE GROUPE 120A 30mA TYPE AC TETRA A9N18542', prix: 870, unite: 'u' },
  { categorie: 'Variateurs RVLED', nom: 'RVLED 250W', prix: 390, unite: 'u' },
  { categorie: 'Variateurs RVLED', nom: 'RVLED 500W', prix: 480, unite: 'u' },
  { categorie: 'Variateurs RVLED', nom: 'RVLED 1000W', prix: 550, unite: 'u' },
  { categorie: 'Variateurs RVLED', nom: 'POTENTIOMETRE ref: 1977', prix: 65, unite: 'u' },
  { categorie: 'Variateurs RVLED', nom: 'SUPPORT POUR POTENTIOMETRE SCHNEIDER ref: A9A15152', prix: 15, unite: 'u' },
  { categorie: 'Variateurs RVLED', nom: 'PUPITRE BB6 ref: 061301', prix: 680, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'TELECOMMANDE DE BAES 062520', prix: 420, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'PEIGNE MONO DT40 SCHNEIDER A9XPN624', prix: 42, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'PEIGNE TETRA SIMPLE IDT40 24 MODULES A9XPP724', prix: 110, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'PEIGNE TETRA SORTIE PAR LE HAUT POUR IC60 24 MODULES R9PXH424', prix: 48, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'BORNES VIKING 37160 LEGRAND', prix: 2, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'PEIGNES VIKING 10 BLOCS 37501 LEGRAND', prix: 7, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'COLLECTEUR DE TERRE POUR 24 MODULES', prix: 105, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'OBTURATEUR 18 MODULES 001664 LEGRAND', prix: 12, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'BAES LEGRAND 062525', prix: 175, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'BAES URA ONE 111013V', prix: 155, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'CENTRALE POUR POWER TAG A9XELC10', prix: 390, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'POWER TAG C - CAPTEUR RADIO FREQUENCE MODULAIRE A9XMC1D3', prix: 220, unite: 'u' },
  { categorie: 'Autres modulaires', nom: 'REPARTITEUR ETAGE TETRAPOLAIRE- 100A - 4x7 trous SCHNEIDER LGY410028', prix: 45, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'INTERUPTEUR PLEXO SAILLIE SIMPLE 069711L', prix: 15, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE PLEXO SAILLIE SIMPLE 069731L', prix: 22, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE PLEXO SAILLIE DOUBLE HORIZONTAL / VERTICAL 069768L', prix: 42, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE PLEXO SAILLIE TRIPLE HORIZONTAL / VERTICAL 069680L + 069564L', prix: 86, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'SORTIE DE CABLE 16A ENCASTRE 069848L', prix: 40, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'ADAPTATEUR A VOLET TRANSPARENT 069580L + 1 POSTE 069681L', prix: 24, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE TETRA SAILLIE 20A 091657', prix: 76, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'FICHE TETRA 20A 055637', prix: 40, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'BOITE PLEXO DIAMETRE 60 (RONDE) 092003', prix: 8, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'BOITE PLEXO DIAMETRE 80 (CARREE) 092013', prix: 12, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'BOITE PLEXO DIAMETRE 100 (CARREE) 092020', prix: 22, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'POT ENCASTRE SIMPLE 080051', prix: 3, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'POT ENCASTRE DOUBLE 080052', prix: 11, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'POT ENCASTRE TRIPLE 080053', prix: 13, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'POT ENCASTRE 2X3 (6 PRISES) 080126', prix: 30, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'INTERUPTEUR PLEXO ENCASTRE SIMPLE 069811L', prix: 24, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE PLEXO ENCASTRE SIMPLE 080051 + 069551 + 069681 (069831L)', prix: 32, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE PLEXO ENCASTRE DOUBLE HORI ET VERTI 080052 + 069562L + 069683L', prix: 50, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE PLEXO ENCASTRE TRIPLE HORIZONTAL 080053 + 069687L + 069564L', prix: 90, unite: 'u' },
  { categorie: 'Appareillages Plexo', nom: 'PRISE TETRA ENCASTRE 20A 080051 + 055708', prix: 84, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PRISE MOSAIC SIMPLE (MECANISME) 077111L', prix: 9, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PRISE MOSAIC DOUBLE AVEC SEPARATION (MECANISME) 077134', prix: 16, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PRISE MOSAIC TRIPLE AVEC SEPARATION (MECANISME) 077136', prix: 24, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'RJ45 CATEGORIE 5 2 MODULES (MECANISME) 076554', prix: 18, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'RJ45 CATEGORIE 5 1 MODULE (MECANISME) 079452', prix: 22, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'INTERRUPTEUR MOSAIC 2 MODULES (MECANISME) 077011L', prix: 10, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'INTERRUPTEUR MOSAIC 1 MODULE (MECANISME) 077001L', prix: 10, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'BOUTON POUSSOIR 2 MODULES (MECANISME) 077040L', prix: 16, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'OBTURATEUR MOSAIC 2 MODULES (MECANISME) 077071', prix: 6, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'SORTIE DE CABLES MOSAIC (MECANISME) 077550', prix: 13, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'SUPPORT ENCASTRE SIMPLE 080251', prix: 3, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'SUPPORT ENCASTRE DOUBLE 080252', prix: 6, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'SUPPORT ENCASTRE TRIPLE 080253', prix: 13, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'SUPPORT ENCASTRE 2X3 (6 PRISES) 080266', prix: 24, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'CADRE SAILLIE SIMPLE 080281', prix: 5.3, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'CADRE SAILLIE DOUBLE HORIZONTAL 080285', prix: 10, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'CADRE SAILLIE DOUBLE VERTICAL', prix: 0, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'CADRE SAILLIE TRIPLE HORIZONTAL', prix: 0, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'CADRE SAILLIE TRIPLE VERTICAL', prix: 0, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'CADRE SAILLIE 2X6 (6 PRISES) 080276', prix: 44, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PLAQUE BLANC SIMPLE MOSAIC 078802L', prix: 3, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PLAQUE BLANC DOUBLE HORIZONTAL AVEC SEPARATION', prix: 6.6, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PLAQUE BLANC DOUBLE VERTICAL AVEC SEPARATION 078822L', prix: 7, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PLAQUE BLANC TRIPLE HORIZONTAL AVEC SEPARATION 078806L', prix: 10, unite: 'u' },
  { categorie: 'Appareillage Mosaic', nom: 'PLAQUE BLANC TRIPLE VERTICAL AVEC SEPARATION 078823L', prix: 12, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'PRISE ENCASTRE SIMPLE MOSAIC 080051 + 077111L + 080251 + 078802L', prix: 17, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'PRISE ENCASTRE DOUBLE MOSAIC 080052 + 077134 + 080252 + 078804L', prix: 40, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'PRISE ENCASTRE TRIPLE MOSAIC 080053 + 077136 + 080253 + 078806L', prix: 60, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'PRISES ENCASTRE MOSAIC 2X3 (6 PRISES) 080126 + 077136 X2 + 080266 + 078832L', prix: 130, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'SORTIE DE CABLE ENCASTRE 080051 + 077550 + 080251 + 078802L', prix: 22, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'PRISE RJ45 ENCASTRE 080051 + 076554 + 080251 + 078802L', prix: 27, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'INTER SIMPLE ENCASTRE 080051 + 077011L + 080251 + 078802L', prix: 19, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: 'INTER DOUBLE ENCASTRE 080051 + 077001L X2 + 080251 + 078802L', prix: 28, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: '6 PRISES EN SAILLIE MOSAIC 077136 X2 + 080266 + 080276 + 078832L', prix: 160, unite: 'u' },
  { categorie: 'Composition Mosaic (encastrÃ©)', nom: '6 PRISES ENCASTRE MOSAIC 077136 X2 + 080266 + 080126 + 078832L', prix: 160, unite: 'u' },
  { categorie: 'Goulottes et Moulures', nom: 'MOULURE OPTIMA TM 34x16 1 COMPARTIMENT BLANCHE IBOCO IBOB08804', prix: 11, unite: 'm' },
  { categorie: 'Eclairage', nom: 'REGLETTE 1,20m HAUTE TEMPERATURE POUR HOTTE NORKA: 4334803421', prix: 720, unite: 'u' },
  { categorie: 'Eclairage', nom: 'REGLETTE 1,20m LED ETANCHE DOUBLE ENTREE TRILUX : TRI7077740', prix: 80, unite: 'u' },
  { categorie: 'Eclairage', nom: 'REGLETTE 1,50m LED ETANCHE TRILUX : 7077640', prix: 90, unite: 'u' },
  { categorie: 'Eclairage', nom: 'SPOT NOIR ORANGÉ 30W EUROLITE LED IP FL-30 SMD (THOMANN)', prix: 70, unite: 'u' },
  { categorie: 'Ampoules (Girard Sudron)', nom: 'E27 2W 2000K 120lm / NON DIMMABLE / SPHERIQUE (GUIRLANDE) 716630', prix: 8, unite: 'u' },
  { categorie: 'Ampoules (Girard Sudron)', nom: 'E27 4W 2200K 260lm / DIMMABLE / SPHERIQUE (GUIRLANDE) 165458', prix: 9, unite: 'u' },
  { categorie: 'Mano Mano Pro', nom: 'GUIRLANDE GUINGUETTE CABLE PLAT NOIRE 12m / 24 DOUILLES E27', prix: 125, unite: 'u' },
  { categorie: 'On Off', nom: 'AMPOULES GU10 / 7W / 2700K / DIMMABLE / SMD2835', prix: 10, unite: 'u' },
  { categorie: 'On Off', nom: 'DOUILLE GU10', prix: 1.4, unite: 'u' },
  { categorie: 'On Off', nom: 'RUBILIGHT COB480 / 2200K / 24VDC / 15W / IP20 / RUBAN DE 5mL', prix: 35, unite: 'm' },
  { categorie: 'On Off', nom: 'PROFILE MINI-LUCI ALU 17,3 X 7mm / LONGUEUR 2,50m', prix: 15, unite: 'm' },
  { categorie: 'On Off', nom: 'CAPOT BLANC LOLA-POLY / LONGUEUR 2,50m', prix: 12, unite: 'm' },
  { categorie: 'On Off', nom: 'TRANSFO 24V / 100W NON DIMMABLE', prix: 105, unite: 'u' },
  { categorie: 'On Off', nom: 'TRANSFO 24V / 150W DIMMABLE', prix: 190, unite: 'u' },
  { categorie: 'On Off', nom: 'CABLE 2X1,5 PLAT NOIR ET ROUGE / 100M (SONEPAR)', prix: 1.8, unite: 'm' },
  { categorie: 'On Off', nom: 'HUBLOT ETANCHE SANS DETECTEUR / DIAMETRE 300mm / 20W / IP 66', prix: 90, unite: 'u' },
  { categorie: 'On Off', nom: 'HUBLOT ETANCHE AVEC DETECTEUR / DIAMETRE 300mm / IP 66', prix: 115, unite: 'u' },
  { categorie: 'On Off', nom: 'REGLETTE LED ETANCHE SANS DETECTEUR 1,20M / 36 W', prix: 110, unite: 'u' },
  { categorie: 'On Off', nom: 'REGLETTE LED ETANCHE AVEC DETECTEUR 1,20M / 36W', prix: 130, unite: 'u' },
  { categorie: 'On Off', nom: 'PROJECTEUR EXTERIEUR NOIR IP65 30W BLANC DU JOUR', prix: 80, unite: 'u' },
  { categorie: 'On Off', nom: 'PROJECTEUR EXTERIEUR NOIR IP65 50W BLANC DU JOUR', prix: 135, unite: 'u' },
  { categorie: 'On Off', nom: 'PROJECTEUR EXTERIEUR NOIR IP65 80W BLANC DU JOUR', prix: 135, unite: 'u' },
  { categorie: 'On Off', nom: 'BRAS DE FIXATION 60CM POUR PROJECTEUR PROJILED', prix: 30, unite: 'u' },
  { categorie: 'Alarme Incendie Type 4 Neutronic', nom: 'DECLENCHEUR MANUEL : NEU5710R1CRF3', prix: 0, unite: 'u' },
  { categorie: 'Alarme Incendie Type 4 Neutronic', nom: 'SIRENE : NEUTT4DSRF3', prix: 0, unite: 'u' },
  { categorie: 'Alarme Incendie Type 4 Neutronic', nom: 'SIRENE + LUMINEUX : NEUTT4DSLRF3', prix: 0, unite: 'u' },
  { categorie: 'Alarme Incendie Type 4 Neutronic', nom: 'CENTRALE TYPE 4 : NEUTT4PRF3', prix: 0, unite: 'u' },
  { categorie: 'Alarme Incendie Type 4 Neutronic', nom: 'PASSAGE DU BUREAU DE CONTROL (RISK CONTROL)', prix: 550, unite: 'u' },
];
